"""
Behavioral Cloning (BC) Supervised Pre-Training for Mini Metro.

Bootstraps MiniMetroActorCritic neural network weights from offline expert demonstrations
generated by GreedyHeuristicPolicy / ModelLiveAgentPolicy.

Minimizes masked cross-entropy loss against expert actions, establishing high-performing
topological and dispatch priors before PPO reinforcement learning.
"""

import os
import sys
import argparse
import time
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
if SCRIPT_DIR not in sys.path:
    sys.path.insert(0, SCRIPT_DIR)

from model import MiniMetroActorCritic
from agent import load_model, get_checkpoint_priority

DEFAULT_DATASET = os.path.join(SCRIPT_DIR, "runs", "expert_dataset.npz")
DEFAULT_CHECKPOINT_DIR = os.path.join(SCRIPT_DIR, "runs", "minimetro_ppo")


class MiniMetroExpertDataset(Dataset):
    def __init__(self, npz_path: str):
        if not os.path.exists(npz_path):
            raise FileNotFoundError(f"Expert dataset not found at: {npz_path}")
        
        data = np.load(npz_path)
        self.nodes = torch.from_numpy(data["nodes"]).float()           # (N, 30, 32)
        # Transpose edges to (2, 200) for PyG / GNN message passing
        edges_np = data["edges"]                                       # (N, 200, 2)
        self.edges = torch.from_numpy(edges_np).long().permute(0, 2, 1) # (N, 2, 200)
        self.edge_attrs = torch.from_numpy(data["edge_attrs"]).float() # (N, 200, 10)
        self.globals = torch.from_numpy(data["globals"]).float()       # (N, 23)
        self.action_masks = torch.from_numpy(data["action_masks"]).bool() # (N, 4087)
        self.num_nodes = torch.from_numpy(data["num_nodes"]).int()     # (N, 1)
        self.num_edges = torch.from_numpy(data["num_edges"]).int()     # (N, 1)
        self.actions = torch.from_numpy(data["actions"]).long()         # (N,)

        self.length = len(self.actions)

    def __len__(self):
        return self.length

    def __getitem__(self, idx):
        return {
            "nodes": self.nodes[idx],
            "edges": self.edges[idx],
            "edge_attrs": self.edge_attrs[idx],
            "globals": self.globals[idx],
            "action_mask": self.action_masks[idx],
            "num_nodes": self.num_nodes[idx],
            "num_edges": self.num_edges[idx],
            "action": self.actions[idx],
        }


def run_bc_training(
    dataset_path: str = DEFAULT_DATASET,
    checkpoint_dir: str = DEFAULT_CHECKPOINT_DIR,
    epochs: int = 15,
    batch_size: int = 64,
    lr: float = 3e-4,
    hidden_dim: int = 256,
    device_name: str = None,
    pretrained: str = None,
):
    if device_name:
        device = torch.device(device_name)
    elif torch.cuda.is_available():
        device = torch.device("cuda")
    else:
        device = torch.device("cpu")

    os.makedirs(checkpoint_dir, exist_ok=True)
    dataset = MiniMetroExpertDataset(dataset_path)
    total_samples = len(dataset)
    val_size = max(100, int(0.10 * total_samples))
    train_size = total_samples - val_size

    train_ds, val_ds = torch.utils.data.random_split(dataset, [train_size, val_size])
    train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True, drop_last=True)
    val_loader = DataLoader(val_ds, batch_size=batch_size, shuffle=False)

    print("=" * 70)
    print("MINI METRO: BEHAVIORAL CLONING (BC) SUPERVISED PRE-TRAINING")
    print(f"Dataset            : {dataset_path} ({total_samples} samples)")
    print(f"Train / Val Split  : {train_size} / {val_size}")
    print(f"Hidden Dimension   : {hidden_dim}")
    print(f"Compute Engine     : {device}")
    print(f"Epochs / Batch Size: {epochs} / {batch_size}")
    print("=" * 70)

    # Initialize model
    if pretrained and os.path.exists(pretrained):
        print(f"[BC] Initializing from pretrained weights: {pretrained}")
        model, _ = load_model(device, model_override=pretrained)
    else:
        model = MiniMetroActorCritic(hidden_dim=hidden_dim).to(device)

    optimizer = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=1e-4)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs)

    best_val_acc = 0.0
    best_model_path = os.path.join(checkpoint_dir, "model_bc.pt")

    for epoch in range(1, epochs + 1):
        model.train()
        train_loss = 0.0
        train_correct = 0
        train_total = 0

        t0 = time.time()
        for batch in train_loader:
            obs = {
                "nodes": batch["nodes"].to(device),
                "edges": batch["edges"].to(device),
                "edge_attrs": batch["edge_attrs"].to(device),
                "globals": batch["globals"].to(device),
                "action_mask": batch["action_mask"].to(device),
                "num_nodes": batch["num_nodes"].to(device),
                "num_edges": batch["num_edges"].to(device),
            }
            targets = batch["action"].to(device)
            mask = obs["action_mask"].bool()

            optimizer.zero_grad()
            logits, _, _ = model(obs, mask=mask)
            logits = logits.masked_fill(~mask, -1e9)

            loss = F.cross_entropy(logits, targets)
            loss.backward()
            nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()

            preds = torch.argmax(logits, dim=-1)
            train_loss += loss.item() * targets.size(0)
            train_correct += (preds == targets).sum().item()
            train_total += targets.size(0)

        scheduler.step()
        train_loss /= train_total
        train_acc = train_correct / train_total

        # Validation loop
        model.eval()
        val_loss = 0.0
        val_correct = 0
        val_total = 0

        with torch.no_grad():
            for batch in val_loader:
                obs = {
                    "nodes": batch["nodes"].to(device),
                    "edges": batch["edges"].to(device),
                    "edge_attrs": batch["edge_attrs"].to(device),
                    "globals": batch["globals"].to(device),
                    "action_mask": batch["action_mask"].to(device),
                    "num_nodes": batch["num_nodes"].to(device),
                    "num_edges": batch["num_edges"].to(device),
                }
                targets = batch["action"].to(device)
                mask = obs["action_mask"].bool()

                logits, _, _ = model(obs, mask=mask)
                logits = logits.masked_fill(~mask, -1e9)
                loss = F.cross_entropy(logits, targets)

                preds = torch.argmax(logits, dim=-1)
                val_loss += loss.item() * targets.size(0)
                val_correct += (preds == targets).sum().item()
                val_total += targets.size(0)

        val_loss /= val_total
        val_acc = val_correct / val_total
        elapsed = time.time() - t0

        is_best = val_acc > best_val_acc
        if is_best:
            best_val_acc = val_acc
            torch.save({
                "model_state_dict": model.state_dict(),
                "epoch": epoch,
                "val_acc": val_acc,
                "hidden_dim": hidden_dim,
                "best_avg_score": 150.0,
            }, best_model_path)
            # Also save as model_best.pt if superior
            torch.save({
                "model_state_dict": model.state_dict(),
                "epoch": epoch,
                "val_acc": val_acc,
                "hidden_dim": hidden_dim,
                "best_avg_score": 150.0,
            }, os.path.join(checkpoint_dir, "model_best.pt"))

        print(f"Epoch {epoch:02d}/{epochs:02d} [{elapsed:.1f}s] | Train Loss: {train_loss:.4f} Acc: {train_acc*100:.1f}% | Val Loss: {val_loss:.4f} Acc: {val_acc*100:.1f}% {'*BEST*' if is_best else ''}", flush=True)

    print("\n" + "=" * 70)
    print(f"[BC] Behavioral Cloning completed! Best Val Accuracy: {best_val_acc*100:.2f}%")
    print(f"[BC] Saved best checkpoint to: {best_model_path}")
    print("=" * 70)


def parse_args():
    parser = argparse.ArgumentParser(description="Mini Metro Behavioral Cloning Trainer")
    parser.add_argument("--dataset", type=str, default=DEFAULT_DATASET, help="Path to expert dataset .npz")
    parser.add_argument("--checkpoint-dir", type=str, default=DEFAULT_CHECKPOINT_DIR, help="Checkpoint output directory")
    parser.add_argument("--epochs", type=int, default=15, help="Training epochs")
    parser.add_argument("--batch-size", type=int, default=64, help="Batch size")
    parser.add_argument("--lr", type=float, default=3e-4, help="Learning rate")
    parser.add_argument("--hidden-dim", type=int, default=256, help="Model hidden dimension")
    parser.add_argument("--device", type=str, default=None, help="Compute device (cpu, cuda)")
    parser.add_argument("--pretrained", type=str, default=None, help="Pretrained checkpoint path")
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    run_bc_training(
        dataset_path=args.dataset,
        checkpoint_dir=args.checkpoint_dir,
        epochs=args.epochs,
        batch_size=args.batch_size,
        lr=args.lr,
        hidden_dim=args.hidden_dim,
        device_name=args.device,
        pretrained=args.pretrained,
    )
